### ISSUE TITLE
Trojan detected in V4W_Setup_x64.exe (both virustotal.com and antivirus detected it)

### ISSUE THREAD

**Issue by githubbc1** [alanfox2000/non-official-viper4windows#11]
V4W_Setup_x64.exe  has a trojan detected by virustotal.com and also anti-virus software in my pc!

Could you please help by getting the 64bit viper uploaded without virus/malware?

Thanks in advance

**Comment by alanfox2000** [comment]
Fix on 1.0.5.4
https://github.com/alanfox2000/non-official-viper4windows/releases/tag/1.0.5.4

**Comment by githubbc1** [comment]
Thank You!

After installing this , couldnt get viper to work on WIndows 10 Home.
Ran Viperfxconfigurator too, still there is no effect of Viper.

The old Viper4windows official works on another windows 8.1 fine though.
