### ISSUE TITLE
Kaspersky is detecting the ViperSetup installation file as "trojan.win32.alien.epn"

### ISSUE THREAD

**Issue by chetan1836** [alanfox2000/non-official-viper4windows#6]
![annotation 2018-12-30 214958](https://user-images.githubusercontent.com/18496456/50549097-ef31b100-0c7c-11e9-8fb5-e0b42f49737c.jpg)

**Comment by alanfox2000** [comment]
V4W_Setup_x64.exe 1.0.5.3
SHA256: 34567f27e394789b99134f20f3425405412182bcf7cb853f047dd8340a554010y
https://www.virustotal.com/#/file/34567f27e394789b99134f20f3425405412182bcf7cb853f047dd8340a554010/detection

**Comment by alanfox2000** [comment]
False-positive. I had seen some report on Advanced Installer forum EXE installer built with Advanced Installer  (my x64 V4W installed use Advanced Installer) detected as containing virus. No idea how to fix Advanced Installer problem. I have rebuilt the x64 installer (11/2/2019) with the latest version of Advanced Installer and reupload to github.

64-bit (11/2/2019)
V4W_Setup_x64.exe
SHA256: f68fa9bfdfa0e98ef57519a8ca57e055826d0483dd4a99559b79addb4d92f30f
https://www.virustotal.com/#/file/f68fa9bfdfa0e98ef57519a8ca57e055826d0483dd4a99559b79addb4d92f30f/detection
[Imgur](https://i.imgur.com/UMjOXaK.png)

**Comment by alanfox2000** [comment]
Fix on 1.0.5.4
https://github.com/alanfox2000/non-official-viper4windows/releases/tag/1.0.5.4
